from flask import Flask
import flask.scaffold
flask.helpers._endpoint_from_view_func = flask.scaffold._endpoint_from_view_func
from flask_restful import Api, Resource
from app.gestor import db
from app.rutas import *
import os
app = Flask(__name__)
api = Api(app)
@app.route('/')
def index():
	return '<h1>Migracion Satisfactoria</h1>'
api.add_resource(RutaAccesos, '/api/accesos')
api.add_resource(RutaAcompanante, '/api/acompanante')
api.add_resource(RutaAgencias, '/api/agencias')
api.add_resource(RutaAlmacen, '/api/almacen')
api.add_resource(RutaAperturas, '/api/aperturas')
api.add_resource(RutaAreas, '/api/areas')
api.add_resource(RutaArticulo, '/api/articulo')
api.add_resource(RutaArticuloproveedor, '/api/articuloproveedor')
api.add_resource(RutaArticulotag, '/api/articulotag')
api.add_resource(RutaAsistencia, '/api/asistencia')
api.add_resource(RutaAuditor, '/api/auditor')
api.add_resource(RutaCajachcab, '/api/cajachcab')
api.add_resource(RutaCajachdet, '/api/cajachdet')
api.add_resource(RutaCajadet, '/api/cajadet')
api.add_resource(RutaCajagas, '/api/cajagas')
api.add_resource(RutaCajamv, '/api/cajamv')
api.add_resource(RutaCajati, '/api/cajati')
api.add_resource(RutaCajero, '/api/cajero')
api.add_resource(RutaCajeromv, '/api/cajeromv')
api.add_resource(RutaCanal, '/api/canal')
api.add_resource(RutaCargos, '/api/cargos')
api.add_resource(RutaCategoria, '/api/categoria')
api.add_resource(RutaCliempre, '/api/cliempre')
api.add_resource(RutaColores, '/api/colores')
api.add_resource(RutaComentarios, '/api/comentarios')
api.add_resource(RutaComisionescab, '/api/comisionescab')
api.add_resource(RutaComisionesdet, '/api/comisionesdet')
api.add_resource(RutaCompatible, '/api/compatible')
api.add_resource(RutaCompatibles, '/api/compatibles')
api.add_resource(RutaCompras, '/api/compras')
api.add_resource(RutaConcepto, '/api/concepto')
api.add_resource(RutaCondicion, '/api/condicion')
api.add_resource(RutaConsolidadocab, '/api/consolidadocab')
api.add_resource(RutaConsolidadodet, '/api/consolidadodet')
api.add_resource(RutaCorrelativos, '/api/correlativos')
api.add_resource(RutaDepartamento, '/api/departamento')
api.add_resource(RutaDias, '/api/dias')
api.add_resource(RutaDirecciones, '/api/direcciones')
api.add_resource(RutaDocumentos, '/api/documentos')
api.add_resource(RutaEmpresas, '/api/empresas')
api.add_resource(RutaEscalas, '/api/escalas')
api.add_resource(RutaExistencia, '/api/existencia')
api.add_resource(RutaFormapago, '/api/formapago')
api.add_resource(RutaHabitacion, '/api/habitacion')
api.add_resource(RutaImagenesps, '/api/imagenesps')
api.add_resource(RutaIniciocab, '/api/iniciocab')
api.add_resource(RutaIniciodetalle, '/api/iniciodetalle')
api.add_resource(RutaKardex, '/api/kardex')
api.add_resource(RutaListaprecios, '/api/listaprecios')
api.add_resource(RutaLotes, '/api/lotes')
api.add_resource(RutaMarca, '/api/marca')
api.add_resource(RutaMonedas, '/api/monedas')
api.add_resource(RutaMotivos, '/api/motivos')
api.add_resource(RutaMotivos_caja, '/api/motivos_caja')
api.add_resource(RutaMovimientodet, '/api/movimientodet')
api.add_resource(RutaMovimientoscab, '/api/movimientoscab')
api.add_resource(RutaMovimientosdet, '/api/movimientosdet')
api.add_resource(RutaNbf_anulado, '/api/nbf_anulado')
api.add_resource(RutaNbf_respuesta, '/api/nbf_respuesta')
api.add_resource(RutaOpercom, '/api/opercom')
api.add_resource(RutaOpergast, '/api/opergast')
api.add_resource(RutaOpermv, '/api/opermv')
api.add_resource(RutaOperpag, '/api/operpag')
api.add_resource(RutaOperti, '/api/operti')
api.add_resource(RutaPedidos_cab, '/api/pedidos_cab')
api.add_resource(RutaPedidos_det, '/api/pedidos_det')
api.add_resource(RutaPeriodo, '/api/periodo')
api.add_resource(RutaPersonal, '/api/personal')
api.add_resource(RutaPlanilla_cab, '/api/planilla_cab')
api.add_resource(RutaPlanilla_det, '/api/planilla_det')
api.add_resource(RutaPremisoprecio, '/api/premisoprecio')
api.add_resource(RutaPrestamocab, '/api/prestamocab')
api.add_resource(RutaPrestamodet, '/api/prestamodet')
api.add_resource(RutaPrimercosteo, '/api/primercosteo')
api.add_resource(RutaProcedencia, '/api/procedencia')
api.add_resource(RutaProdtallacolor, '/api/prodtallacolor')
api.add_resource(RutaProductofoto, '/api/productofoto')
api.add_resource(RutaProfesion, '/api/profesion')
api.add_resource(RutaPromocab, '/api/promocab')
api.add_resource(RutaPromodet, '/api/promodet')
api.add_resource(RutaProveedores, '/api/proveedores')
api.add_resource(RutaProvincia, '/api/provincia')
api.add_resource(RutaRegion, '/api/region')
api.add_resource(RutaReservacab, '/api/reservacab')
api.add_resource(RutaReservadet, '/api/reservadet')
api.add_resource(RutaRutas, '/api/rutas')
api.add_resource(RutaSurtidor, '/api/surtidor')
api.add_resource(RutaTabla01, '/api/tabla01')
api.add_resource(RutaTabla02, '/api/tabla02')
api.add_resource(RutaTabla05, '/api/tabla05')
api.add_resource(RutaTabla06, '/api/tabla06')
api.add_resource(RutaTabla10, '/api/tabla10')
api.add_resource(RutaTags, '/api/tags')
api.add_resource(RutaTallas, '/api/tallas')
api.add_resource(RutaTareas, '/api/tareas')
api.add_resource(RutaTempserie, '/api/tempserie')
api.add_resource(RutaTipohabitacion, '/api/tipohabitacion')
api.add_resource(RutaTipomovalmacen, '/api/tipomovalmacen')
api.add_resource(RutaTiporeserva, '/api/tiporeserva')
api.add_resource(RutaTmpsaldos, '/api/tmpsaldos')
api.add_resource(RutaTmptablacompras, '/api/tmptablacompras')
api.add_resource(RutaTmptablaventas, '/api/tmptablaventas')
api.add_resource(RutaTransporte, '/api/transporte')
api.add_resource(RutaTurnos, '/api/turnos')
api.add_resource(RutaUbigeo, '/api/ubigeo')
api.add_resource(RutaUnidades, '/api/unidades')
api.add_resource(RutaUsuarios, '/api/usuarios')
api.add_resource(RutaVendedor, '/api/vendedor')
api.add_resource(RutaZona, '/api/zona')
api.add_resource(RutaZonas, '/api/zonas')

if __name__ == '__main__':
	app.run(debug=True)
